#harness.io/skip-file-for-deploy
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Values.name}}
spec:
  hosts:
  - {{.Values.name}}
  http:
  - match:
    - uri:
       exact: /weatherbyzip
    route:
    - destination:
        host: {{.Values.name}}
        port:
          number: 8081
---