harnessApiVersion: '1.0'
type: GIT
authorName: martin2176
branch: main
delegateSelectors:
- martin-aks2-delegate
disableUserGitConfig: false
keyAuth: false
password: gcpkms:github-password-martin-aug2023
providerType: GITHUB
url: https://github.com/martin2176/harnessconfigascodedemo
urlType: REPO
username: martin2176
