harnessApiVersion: '1.0'
type: PIPELINE
pipelineStages:
- type: ENV_STATE
  name: aksdebugpoddeployment
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 1
  workflowName: aksdebugpoddeployment
  workflowVariables:
  - name: namespace
    value: demo1
rollbackPreviousStages: false
