---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.app}}
    serviceteam: {{.Values.serviceteam}}
    env: {{.Values.env}}
    service: {{.Values.service}}
spec:
  selector:
    app: {{.Values.app}}
    serviceteam: {{.Values.serviceteam}}
    env: {{.Values.env}}
    service: {{.Values.service}}
  ports:
  - port: 8080
    protocol: TCP
    name: http8080
---
