harnessApiVersion: '1.0'
type: ROLLING
concurrencyStrategy: INFRA
envName: development
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupNames:
  - Account Administrator
phases:
- type: KUBERNETES
  computeProviderName: martin-aks2
  daemonSet: false
  infraDefinitionName: martin-aks2
  name: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Create
    stepSkipStrategies:
    - assertionExpression: 1==1
      scope: SPECIFIC_STEPS
      steps:
      - Apply
    steps:
    - type: K8S_APPLY
      name: Apply
      properties:
        delegateSelectors:
        - martin-harness-demo-vm1
        filePaths: aksdebugpod/deployment.yaml,aksdebugpod/service.yaml
        stateTimeoutInMinutes: 2
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
      properties:
        delegateSelectors:
        - martin-harness-demo-vm1
        stateTimeoutInMinutes: 1
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    steps:
    - type: DATA_DOG_LOG
      name: Datadog Log
      properties:
        analysisServerConfigId: kvgug_WhQp-V9yMQvbrOTw
        comparisonStrategy: COMPARE_WITH_CURRENT
        executeWithPreviousSteps: false
        hostnameField: pod_name
        hostnameTemplate: ${instanceDetails.k8s.podName}
        query: kube_namespace:demo1
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeDuration: 5
    stepsInParallel: false
    waitInterval: 15
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: aksdebugpod
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: martin-aks2
  daemonSet: false
  infraDefinitionName: martin-aks2
  name: Rollback Rolling
  phaseNameForRollback: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Delete
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    stepSkipStrategies:
    - assertionExpression: 1==1
      scope: ALL_STEPS
    steps:
    - type: K8S_DELETE
      name: Delete
      properties:
        delegateSelectors:
        - martin-harness-demo-vm1
        deleteNamespacesForRelease: false
        filePaths: aksdebugpod/service.yaml,aksdebugpod/deployment.yaml
        stateTimeoutInMinutes: 1
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: aksdebugpod
  statefulSet: false
templatized: true
userVariables:
- type: TEXT
  allowedValues: demo1,demo2,demo3
  fixed: false
  mandatory: true
  name: namespace
