harnessApiVersion: '1.0'
type: ROLLING
concurrencyStrategy: INFRA
envName: development
phases:
- type: KUBERNETES
  computeProviderName: martin-aks2
  daemonSet: false
  infraDefinitionName: martin-aks2
  name: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
      properties:
        delegateSelectors:
        - martin-harness-demo-vm1
        stateTimeoutInMinutes: 4
        templateUuid: null
        templateVariables: null
        templateVersion: null
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: frontend
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: martin-aks2
  daemonSet: false
  infraDefinitionName: martin-aks2
  name: Rollback Rolling
  phaseNameForRollback: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: frontend
  statefulSet: false
templatized: true
userVariables:
- type: TEXT
  allowedValues: demo1,demo2,demo3
  description: Enter the namespace to deploy this
  fixed: false
  mandatory: true
  name: namespace
