#harness.io/skip-file-for-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: aksdebug
  labels:
    app: aksdebug
    service: aksdebug
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: aksdebug
---